version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t hnclonecphb/database:$CIRCLE_BRANCH .
      - run: docker push hnclonecphb/database:$CIRCLE_BRANCH
      - run: docker build -t hnclonecphb/database:$CIRCLE_WORKFLOW_ID .
      - run: docker push hnclonecphb/database:$CIRCLE_WORKFLOW_ID
  
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "docker service update --mount-add type=bind,source=/mongodb/data,target=/data/db -d --image hnclonecphb/database:$CIRCLE_WORKFLOW_ID database"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
