version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t hnclonecphb/database:$CIRCLE_BRANCH .
      - run: docker push hnclonecphb/database:$CIRCLE_BRANCH
  
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "docker pull hnclonecphb/database:$CIRCLE_BRANCH
            docker stop database 
            docker rm database
            docker run --name database --publish=27017:27017 -d hnclonecphb/database:$CIRCLE_BRANCH"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
